### ISSUE TITLE
How to access eureka server with user/password?

### ISSUE THREAD

**Issue by AmramXing** [SteeltoeOSS/Discovery#12] opened 2017-07-27 09:39 UTC
In java version, I use below setting to access Eureka server which has user/password setting.
...
**eureka.client.serviceUrl.defaultZone=http://user:password@localhost:11001/eureka/**
...
But in Steeltoe .net version, It seem has no effect.Who can help me? 
 
Another question: Steeltoe suport below format(property binding), supprot **_{cipher}_** encryp format?

**eureka.client.serviceUrl.defaultZone=http://${security.user.name}:${security.user.password}@localhost:11001/eureka/
..
security.user.name=user
security.user.password={cipher}xxxxxxx**

**Comment by kkho** [comment] 2017-08-01 12:29
any news about this?

**Comment by kkho** [comment] 2017-08-16 17:51
For me it seems that the only solution is to not have defaultZone. but just the url.  Also the problem is that there are no translation bindings that are the setup. In Spring, its possible to translate properties (i.e. ${vcap.service.username}:....:${serviceurl}/eureka

**Comment by dtillman** [comment] 2017-08-16 23:10
Hi kkho,
Currently the Eureka client does not support Basic Auth (username/password) settings in the serviceUrl.
Likewise, Eureka configuration does not support the Spring Property Place holder feature (e.g. ${blah.blah}
.  
I have had a couple requests to get both of these things added, so I'll look at doing that in the very near future.

I'll leave issue open to track the work

**Comment by nbarboutis** [comment] 2018-06-21 17:12
any progress on this.

**Comment by nbarboutis** [comment] 2018-06-26 20:44
I have a proposed fix for this issue. Let me know if you require any changes. 
Thanks.

**Comment by TimHess** [comment] 2018-06-26 21:43
Thanks @nbarboutis, this feature is available as of `2.1.0-dev-191`!

**Closed by TimHess** 2018-06-26 21:43 UTC
Labels: delivered

**Comment by lukastosic** [comment] 2018-07-03 16:18
@TimHess 

I'm not sure this is included in latest "dev" release ...

When I try to run "FortuneTellerService" sample (from SteeltoeOSS samples repository) with username password I am getting "unauthorized" response

Then I did the following:
1. cloned this git repo
2. switched to dev branch, 
3. open solution in Visual Studio
4. added existing project to solution (FortuneTellerService)
5. removed nuget reference
6. added project reference to this project (Steeltoe.Discovery.ClientCore)

Rebuild, run -> then it was OK.

I used TCPMon to scan requests, and when I used latest dev nuget, there were no Authorization header in request, but when I switched to use "project dependency" then authorization request was there.

**Comment by TimHess** [comment] 2018-07-03 16:47
@lukastosic we don't normally keep the samples in lock-step with dev feed releases. You should be able to just update the Pivotal.Discovery.ClientCore reference from `2.1.0-dev-00172` to `2.1.0-dev-194` to use this feature

**Comment by lukastosic** [comment] 2018-07-04 07:49
@TimHess yeah .. that is what I did the first time I saw this thread - changed reference in sample to "latest" dev version .. 

tried with `2.1.0-dev-194`, but got error that version doesn't exist .. it offered:

```
c:\Users\lstosic\Source\Repos\Fortune-Teller-Service>dotnet run -f netcoreapp2.1
c:\Users\lstosic\Source\Repos\Fortune-Teller-Service\Fortune-Teller-Service.csproj : error NU1102: Unable to find package Pivotal.Discovery.ClientCore with version (>= 2.1.0-dev-194)
c:\Users\lstosic\Source\Repos\Fortune-Teller-Service\Fortune-Teller-Service.csproj : error NU1102:   - Found 66 version(s) in SteeltoeDev [ Nearest version: 2.1.0-dev-00194 ]
c:\Users\lstosic\Source\Repos\Fortune-Teller-Service\Fortune-Teller-Service.csproj : error NU1102:   - Found 5 version(s) in SteeltoeMaster [ Nearest version: 2.0.0-master-00130 ]
c:\Users\lstosic\Source\Repos\Fortune-Teller-Service\Fortune-Teller-Service.csproj : error NU1102:   - Found 3 version(s) in nuget.org [ Nearest version: 2.0.1 ]
c:\Users\lstosic\Source\Repos\Fortune-Teller-Service\Fortune-Teller-Service.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

The build failed. Please fix the build errors and run again.
```

so, then changed to `2.1.0-dev-00194` (two zeros in front of the number)

I sterted TCPmon (made proxy to catch request) and got this as a request:

```
POST /eureka/apps/FORTUNESERVICE HTTP/1.1
Accept: application/json
Content-Type: application/json; charset=utf-8
Content-Length: 1063
Host: 10.4.1.224:5555

{"instance":{"instanceId":"LT07-
.... OTHER POST data about instance ...
}
```

But when I build with that local "project dependency" (instead of nuget) .. I see this in TCPmon:

```
POST /eureka/apps/FORTUNESERVICE HTTP/1.1
Authorization: Basic YWRtaW46RERyV21lbGp6ZTBhY3BhZXFOc3A=
Accept: application/json
Content-Type: application/json; charset=utf-8
Content-Length: 1063
Host: 10.4.1.224:5555

{"instance":{"instanceId":"LT07-Luka.infodation.local:fortuneService:5000"
... OTHER POST data
}
```

"non-nuget" generates proper `Authorization` header

=========================

This is `.csproj` (when I use nuget package)

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.1;net461</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="testcert.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

   <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Https" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.1.0" />
    <PackageReference Include="Pivotal.Discovery.ClientCore" Version="2.1.0-dev-00194" />
    <PackageReference Include="Steeltoe.Extensions.Configuration.CloudFoundryCore" Version="2.1.0-dev-00227" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.1.0" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
  
</Project>
```

This is `nuget.config`

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="SteeltoeMaster" value="https://www.myget.org/F/steeltoemaster/api/v3/index.json" />
    <add key="SteeltoeDev" value="https://www.myget.org/F/steeltoedev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by lukastosic** [comment] 2018-07-05 18:49
@TimHess 

after trying out different things:

1. Git clone samples repository (completely new "clean")
2. Don't run anything ;)
3. Open `Fortune-Teller-Service.csproj` file and adjut `Pivotal.Discovery.ClientCore` version to: `2.1.0-dev-00194`
4. Run app `dotnet run -f netcoreapp2.1`

This one **does not** send authentication header

Then I changed **Pivotal**.Discovery.ClientCore -> **Steeltoe**.Discovery.ClientCore with version `2.1.0-dev-00192`

(Of course because of that also adjust `Startup.cs` import rename "Pivotal" -> "Steeltoe")

This one *DOES* send out authentication header

**Comment by TimHess** [comment] 2018-07-05 19:02
@lukastosic That does make some amount of sense... one of the things the Pivotal library does is handle authentication with Eureka, so it probably shouldn't be surprising that there could be a problem using it and setting username/password.

I've logged a bug to investigate further and see if we could do something other than declare it a known issue, but I don't know when we'll look at it. In the meantime, if anybody does have a need to use both the Pivotal library and the username/password authentication please let us know with a thumbs up or a comment

https://www.pivotaltracker.com/story/show/158848832

**Comment by lukastosic** [comment] 2018-07-05 19:21
@TimHess 

Thanks Tim ... using "just" Steeltoe instead of "Pivotal" libraries is perfectly fine for my case since we will host application in our own environment, so we will not use any Pivotal Cloud services (Cloud foundry) either way ...

**Comment by nbarboutis** [comment] 2018-07-05 20:48
I can look into this. I already download the sample and verified the issue Luka is having.

Are the Pivotal libraries open source so I can download them and debug what going on?

**Comment by TimHess** [comment] 2018-07-05 21:37
@nbarboutis thanks!

For anybody following along, the source for Pivotal.Discovery is over here: https://github.com/pivotal-cf/spring-cloud-dotnet-discovery

**Comment by nbarboutis** [comment] 2018-07-06 12:13
I determined what is causing the issue:

The **PivotalEurekaHttpClient** class, although inheriting from **EurekaHttpClient** is overriding **GetRequestMessage**. The **GetRequestMessage** method in **EurekaHttpClient**  class is where the serviceUrl is parsed for username and password and the appropriate header is added. By overriding this method **PivotalEurekaHttpClient** is bypassing this step and therefore not adding the appropriate header.

I will attempt to fix the issue soon. Will keep you posted.
